obscenity_words = ["baby batter",
"baby juice",
"ball gag",
"ball gravy",
"ball kicking",
"ball licking",
"ball sack",
"ball sucking",
"bangbros",
"bareback",
"barely legal",
"barenaked",
"bastardo",
"bastinado",
"bbw",
"cock"];